### PR TITLE
Change date format

### PR DESCRIPTION
**Pull request by graphicsminded**
Date format now resembles some of the other date formats in:  
Administrator Backend>Extensions>Manage>Manage>Date Column:
- before: 2016-9-26
- after: 9/26/2016

### CODE REVIEW

**Comment by graphicsminded** [comment]
Thank you for such a wonderful Yeoman Extension!

- Scott Nunemacher

**Comment by graphicsminded** [comment]
Wait... I think I might have done this twice. I'm really sorry if that is the case, just trying to help. -Scott

**Comment by fede91it** [comment]
I accepted the PR but very soon I'll release a new major release with supports for components and a fresh new build file, more customizable. I'll add also the customization of the date format as you did here

**Comment by graphicsminded** [comment]
@fede91it thank you so much. Can't wait to see it. I use it for all my extension stuff.

**Pull request merged**
